import React from "react";
import {
  Sun,
  GlassWater,
  Smile,
  Dumbbell,
  Leaf,
  Vegan,
  AlarmClock,
  Pen,
  CigaretteOff,
  Camera,
  CakeSlice,
  BookOpen,
  WineOff,
  Bike,
  Sprout,
  Apple,
  Palette,
  Bed,
  Coffee,
  CalendarCheck,
  CandyOff,
  Dribbble,
  Gamepad2,
  Banana,
  Drum,
} from "lucide-react";

export const IconType: { [key: string]: JSX.Element } = {
  Sun: <Sun />,
  GlassWater: <GlassWater />,
  Smile: <Smile />,
  Dumbbell: <Dumbbell />,
  Leaf: <Leaf />,
  Vegan: <Vegan />,
  AlarmClock: <AlarmClock />,
  Pen: <Pen />,
  CigaretteOff: <CigaretteOff />,
  Camera: <Camera />,
  CakeSlice: <CakeSlice />,
  BookOpen: <BookOpen />,
  WineOff: <WineOff />,
  Bike: <Bike />,
  Sprout: <Sprout />,
  Apple: <Apple />,
  Banana: <Banana />,
  Palette: <Palette />,
  Bed: <Bed />,
  Coffee: <Coffee />,
  CalendarCheck: <CalendarCheck />,
  CandyOff: <CandyOff />,
  Dribbble: <Dribbble />,
  Gamepad2: <Gamepad2 />,
  Drum: <Drum />,
};
